apiVersion: v1
kind: Secret
metadata:
  name: airflow-s3-credentials
type: Opaque
stringData:
  S3_ACCESS_KEY: {{ .Values.ingressService.configuration.s3.secrets.accessKey | quote }}
  S3_SECRET_KEY: {{ .Values.ingressService.configuration.s3.secrets.secretKey | quote }}
  S3_ENDPOINT_URL: {{ .Values.ingressService.configuration.s3.endpointUrl | quote }}
  S3_STORE_URL: {{ .Values.ingressService.configuration.s3.storeUrl | quote }}
