---
{{- with .Values.airflow.webServer  }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name | quote }}
spec:
  replicas: {{ .replicaCount | int }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .name | quote }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .name | quote }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
        app.kubernetes.io/version: {{ $.Chart.AppVersion }}
        app.kubernetes.io/part-of: {{ .partOf | default $.Chart.Name }}
        app.kubernetes.io/component: {{ .component | default $.Chart.Name }}
        app.kubernetes.io/managed-by: {{ $.Release.Service }}
        {{- if .extraLabels }}
        {{- toYaml .extraLabels | nindent 8 }}
        {{- end }}
      annotations:
        github.com/run-id: {{ $.Values.global.runId | quote }}
        {{- if .extraAnnotations }}
        {{- toYaml .extraAnnotations | nindent 8 }}
        {{- end }}
    spec:
      restartPolicy: {{ .restartPolicy }}
      securityContext:
        {{- toYaml .securityContext.pod | nindent 8 }}
      volumes:
        - name: airflow-webserver-logs
          emptyDir: {}
      containers:
        - name: webserver
          image: "{{ $.Values.airflow.image.host }}/{{ $.Values.airflow.image.name }}:{{ $.Values.airflow.image.tag }}"
          imagePullPolicy: {{ $.Values.airflow.imagePullPolicy }}
          args:
            - "webserver"
          ports:
            - name: {{ .service.internalPort.name | quote }}
              containerPort: {{ .service.internalPort.number | int }}
          securityContext:
            {{- toYaml .securityContext.container | nindent 12 }}
          resources:
            {{- toYaml .resources | nindent 12 }}
          envFrom:
            - secretRef:
                name: airflow-secrets
            - secretRef:
                name: airflow-s3-credentials
          volumeMounts:
            - name: airflow-webserver-logs
              mountPath: /opt/airflow/logs
          env:
            {{- toYaml .extraEnv | nindent 12 }}
          startupProbe:
            httpGet:
              path: /api/v2/monitor/health
              port: {{ .service.internalPort.name | quote }}
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 72
          livenessProbe:
            httpGet:
              path: /api/v2/monitor/health
              port: {{ .service.internalPort.name | quote }}
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /api/v2/monitor/health
              port: {{ .service.internalPort.name | quote }}
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 10
{{- end -}}
