apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zarr-fuse-ingress
  annotations:
    {{- toYaml .Values.ingressService.ingress.annotations | nindent 4 }}
  labels:
    {{- toYaml .Values.ingressService.ingress.labels | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingressService.ingress.className | quote }}
  rules:
    - host: zarr-fuse-{{ .Values.ingressService.name }}.dyn.cloud.e-infra.cz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ingressService.service.name | quote }}
                port:
                  name: {{ .Values.ingressService.service.externalPort.name | quote }}
  tls:
    - secretName: zarr-fuse-{{ .Values.ingressService.name }}-dyn-cloud-e-infra-cz-tls
      hosts:
        - zarr-fuse-{{ .Values.ingressService.name }}.dyn.cloud.e-infra.cz
