apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zarr-fuse-ingress
  annotations:
    {{- toYaml .Values.ingressService.ingress.annotations | nindent 4 }}
  labels:
    {{- toYaml .Values.ingressService.ingress.labels | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingressService.ingress.className | quote }}
  rules:
    {{- range .Values.ingressService.ingress.hosts }}
    - host: {{ .name | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $.Values.ingressService.service.name | quote }}
                port:
                  name: {{ $.Values.ingressService.service.externalPort.name | quote }}
    {{- end }}
  tls:
    {{- range .Values.ingressService.ingress.hosts }}
    {{- if .tls.enabled }}
    - secretName: {{ .tls.secretName | quote }}
      hosts:
        - {{ .name | quote }}
    {{- end }}
    {{- end }}
