apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-env-secrets
  labels:
    app.kubernetes.io/name: {{ .Values.app.name }}
type: Opaque
stringData:
  ZF_S3_ENDPOINT_URL: {{ required "S3_ENDPOINT_URL needs to be set" .Values.deployment.secrets.s3.endpointUrl | quote }}
  ZF_S3_ACCESS_KEY: {{ required "S3_ACCESS_KEY needs to be set" .Values.deployment.secrets.s3.accessKey | quote }}
  ZF_S3_SECRET_KEY: {{ required "S3_SECRET_KEY needs to be set" .Values.deployment.secrets.s3.secretKey | quote }}
  ZF_STORE_URL: {{ required "S3_STORE_URL needs to be set" .Values.deployment.secrets.s3.storeUrl | quote }}
  BASIC_AUTH_USERS_JSON: {{ required "BASIC_AUTH_USERS_JSON needs to be set" .Values.deployment.secrets.basicAuth.usersJson | toJson | quote }}
  QUEUE_DIR: {{ .Values.deployment.queue.path | quote }}
