apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        app.kubernetes.io/part-of: {{ .Values.partOf | default .Chart.Name }}
        app.kubernetes.io/component: {{ .Values.component | default .Chart.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        {{- if .Values.extraLabels }}
        {{- toYaml .Values.extraLabels | nindent 8 }}
        {{- end }}
      annotations:
        github.com/run-id: {{ .Values.global.runId | quote }}
        checksum/config: '{{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}'
        {{- if .Values.extraAnnotations }}
        {{- toYaml .Values.extraAnnotations | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
        {{- toYaml .Values.securityContext.pod | nindent 8 }}
      volumes:
        - name: ingress-server-tmp
          emptyDir: {}
      restartPolicy: {{ .Values.restartPolicy }}
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.host }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - name: {{ .Values.service.internalPort.name | quote }}
              containerPort: {{ .Values.service.internalPort.number | int }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext.container | nindent 12 }}
          env:
            {{- toYaml .Values.extraEnv | nindent 12 }}
          envFrom:
            - secretRef:
                name: ingress-service-env-secrets
          volumeMounts:
            - name: ingress-server-tmp
              mountPath: /tmp
          startupProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.internalPort.name | quote }}
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 72
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.internalPort.name | quote }}
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.internalPort.name | quote }}
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 10
