apiVersion: v1
kind: Secret
metadata:
  name: ingress-service-env-secrets
type: Opaque
stringData:
  S3_ACCESS_KEY: {{ .Values.global.s3.secrets.accessKey | quote }}
  S3_SECRET_KEY: {{ .Values.global.s3.secrets.secretKey | quote }}
  S3_ENDPOINT_URL: {{ .Values.global.s3.endpointUrl | quote }}
  S3_STORE_URL: {{ .Values.global.s3.storeUrl | quote }}
  BASIC_AUTH_USERS_JSON: {{ .Values.configuration.fastapi.secrets.usersJson | toJson | quote }}
