apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | quote }}
  labels:
    {{- toYaml .Values.service.labels | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ .Values.name }}
  ports:
    - name: {{ .Values.service.externalPort.name | quote }}
      port: {{ .Values.service.externalPort.number | int }}
      targetPort: {{ .Values.service.internalPort.name | quote }}
