global:
  s3:
    storeUrl: "s3://app-databuk-test-service/bukov-pull-request.zarr"
ingress:
  hosts:
    ingressService:
      - name: zarr-fuse-ingress-server-development.dyn.cloud.e-infra.cz
        tls:
          enabled: true
          secretName: zarr-fuse-ingress-server-development-dyn-cloud-e-infra-cz-tls
    extractorService:
      - name: zarr-fuse-airflow-development.dyn.cloud.e-infra.cz
        tls:
          enabled: true
          secretName: zarr-fuse-airflow-development-dyn-cloud-e-infra-cz-tls
ingressService:
  name: ingress-service-development
  service:
    name: ingress-service-development
