global:
  s3:
    storeUrl: "s3://app-databuk-release-service/bukov.zarr"
ingress:
  hosts:
    ingressService:
      - name: zarr-fuse-ingress-server.dyn.cloud.e-infra.cz
        tls:
          enabled: true
          secretName: zarr-fuse-ingress-server-dyn-cloud-e-infra-cz-tls
    extractorService:
      - name: zarr-fuse-airflow.dyn.cloud.e-infra.cz
        tls:
          enabled: true
          secretName: zarr-fuse-airflow-dyn-cloud-e-infra-cz-tls
ingressService:
  name: ingress-server
  service:
    name: ingress-server
