global:
  s3:
    storeUrl: "s3://app-databuk-test-service/testing-airflow.zarr"
ingress:
  hosts:
    - name: zarr-fuse-ingress-server-testing.dyn.cloud.e-infra.cz
      tls:
        enabled: true
        secretName: zarr-fuse-ingress-server-testing-dyn-cloud-e-infra-cz-tls
ingressService:
  name: ingress-service-testing
  service:
    name: ingress-service-testing
