[project]
name = "packages"
description = "Packages shared across databuk ingress server services"
version = "0.1.0"
requires-python = ">=3.11"
authors = [
  { name = "Jan Brezina", email = "jan.brezina@tul.cz" },
  { name = "Stepan Moc", email = "stepan.mocik@gmail.com" },
]
maintainers = [{ name = "Stepan Moc", email = "stepan.mocik@gmail.com" }]
license = "BSD-3-Clause"
keywords = ["Airflow", "Zarr_fuse", "Zarr", "s3"]

dependencies = [
  "boto3==1.40.49",
  "pydantic==2.12.3",
  "polars==1.34.0",
  "python-dotenv==1.2.1",
  "pyyaml==6.0.3",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["packages", "packages.*"]

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"
