apiVersion: v1
kind: Secret
metadata:
  name: ingress-service-env-var-secrets
type: Opaque
stringData:
  S3_ACCESS_KEY: {{ required "S3_ACCESS_KEY needs to be set" .Values.ingressService.configuration.s3.secrets.accessKey | quote }}
  S3_SECRET_KEY: {{ required "S3_SECRET_KEY needs to be set" .Values.ingressService.configuration.s3.secrets.secretKey | quote }}
  S3_ENDPOINT_URL: {{ required "S3_ENDPOINT_URL needs to be set" .Values.ingressService.configuration.s3.endpointUrl | quote }}
  S3_STORE_URL: {{ required "S3_STORE_URL needs to be set" .Values.ingressService.configuration.s3.storeUrl | quote }}
  BASIC_AUTH_USERS_JSON: {{ required "BASIC_AUTH_USERS_JSON needs to be set" .Values.ingressService.configuration.fastapi.security.usersJson | toJson | quote }}
